version: '3.8'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://unifei:unifei@db:5432/FDA_database
    depends_on:
      - db
    networks:
      - app-network
    volumes:
      - .:/app
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

          
  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=unifei
      - POSTGRES_PASSWORD=unifei
      - POSTGRES_DB=FDA_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
